/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.konek;
import objectclass.*;

/**
 *
 * @author ASUS
 */
public class addpage extends javax.swing.JFrame {
    
//    private sepatu sp;
    
    //deklarasi
    private String kode;
//    private String brand;
//    private String product;
    private String nmproduct;
    private String warna;
    private int ukuran;
    private String harga;
    
    public DefaultTableModel model;
    public Statement st;
    public Connection conn;
    public ResultSet rs;
    

    /**
     * Creates new form addpage
     */
    public addpage() {
        initComponents();
    }
    
//    public void tampil(String kd){
//        try{
//            konek koneksi = new konek();
//            st = conn.createStatement();
//            String sql="SELECT * FROM sneakers where Kode='"+ kd +"'";
//            rs = st.executeQuery(sql);
//            if(rs.next()){
//               cmbbrand.setSelectedItem(rs.getString("Brand"));
//               if(rs.getString("Brand").equals("Local Brand")){
//                   cmblocal.setSelectedItem(rs.getString("Product"));
//               }else if (rs.getString("Brand").equals("International Brand")){
//                   
//               }
//               tkode.setText(rs.getString("Kode"));
//               tnamaproduk.setText(rs.getString("Nama product"));
//               twarna.setText(rs.getString("Warna"));
//               tsize.setText(rs.getString("Ukuran"));
//               tharga.setText(rs.getString("Harga"));
//            }else{
//                JOptionPane.showMessageDialog(null, "Sepatu Tidak Tersedia");
//            }
//        }catch (Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        cmbbrand = new javax.swing.JComboBox<>();
        cmblocal = new javax.swing.JComboBox<>();
        btlogout = new javax.swing.JButton();
        btabout = new javax.swing.JButton();
        btmenu = new javax.swing.JButton();
        btcatalog = new javax.swing.JButton();
        btdata = new javax.swing.JButton();
        tnamaproduk = new javax.swing.JTextField();
        tsize = new javax.swing.JTextField();
        tharga = new javax.swing.JTextField();
        bthapus = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        tkode = new javax.swing.JTextField();
        twarna = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbbrand.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cmbbrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==Brand==", "Local ", "International " }));
        cmbbrand.setBorder(null);
        cmbbrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbrandActionPerformed(evt);
            }
        });
        getContentPane().add(cmbbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 290, 40));

        cmblocal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        cmblocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=pilih produk=", "==Local==", "Compass", "Nah Project", "Ventela", "Piero", "==International==", "Nike", "Balenciaga", "Louis Vuitton", "Yeezy" }));
        cmblocal.setBorder(null);
        cmblocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmblocalActionPerformed(evt);
            }
        });
        getContentPane().add(cmblocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 210, 40));

        btlogout.setContentAreaFilled(false);
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 50, 40));

        btabout.setContentAreaFilled(false);
        btabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaboutActionPerformed(evt);
            }
        });
        getContentPane().add(btabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 80, 60));

        btmenu.setContentAreaFilled(false);
        btmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 70));

        btcatalog.setContentAreaFilled(false);
        btcatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcatalogActionPerformed(evt);
            }
        });
        getContentPane().add(btcatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 70));

        btdata.setContentAreaFilled(false);
        btdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdataActionPerformed(evt);
            }
        });
        getContentPane().add(btdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 80, 50));

        tnamaproduk.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tnamaproduk.setBorder(null);
        tnamaproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaprodukActionPerformed(evt);
            }
        });
        getContentPane().add(tnamaproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 380, 30));

        tsize.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tsize.setBorder(null);
        getContentPane().add(tsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 370, 30));

        tharga.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tharga.setBorder(null);
        getContentPane().add(tharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 310, 30));

        bthapus.setContentAreaFilled(false);
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });
        getContentPane().add(bthapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, 160, 30));

        btadd.setContentAreaFilled(false);
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        getContentPane().add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 640, 160, 40));

        tkode.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tkode.setBorder(null);
        getContentPane().add(tkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 180, 30));

        twarna.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        twarna.setBorder(null);
        getContentPane().add(twarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 380, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/catalog.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlogoutActionPerformed

    private void cmbbrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbrandActionPerformed
//        if (cmbbrand.getSelectedItem().equals("Local Brand")){
//            
//            cmblocal.setEnabled(true);
//        }else if(cmbbrand.getSelectedItem().equals("International Brand")){
//            cmblocal.setEnabled(false);
//            
//        }
    }//GEN-LAST:event_cmbbrandActionPerformed

    private void cmblocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmblocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmblocalActionPerformed

    private void btmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmenuActionPerformed
       new Menupage().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btmenuActionPerformed

    private void btcatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcatalogActionPerformed
        new catalogpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcatalogActionPerformed

    private void btdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdataActionPerformed
        new datapage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btdataActionPerformed

    private void btaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaboutActionPerformed
        new aboutpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btaboutActionPerformed

    private void tnamaprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaprodukActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        tnamaproduk.setText("");
        cmbbrand.setSelectedItem("==Brand==");
        cmblocal.setSelectedItem("==Local==");
        
        tsize.setText("");
        tharga.setText("");
        twarna.setText("");
        tkode.setText("");
    }//GEN-LAST:event_bthapusActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        try{
            String sql="insert into sneaky VALUES (?,?,?,?,?,?,?)";
            java.sql.Connection conn=(Connection)konek.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1, (String) tkode.getText());
            pst.setString(2, (String) cmbbrand.getSelectedItem());
//            pst.setString(3, (String) cmbinter.getSelectedItem());
            pst.setString(3, (String) cmblocal.getSelectedItem());
            pst.setString(4, (String) tnamaproduk.getText());
            pst.setString(5, (String) twarna.getText());
            pst.setString(6, (String) tsize.getText());
            pst.setString(7, (String) tharga.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Sepatu "+tnamaproduk.getText()+" Berhasil Ditambahkan!");      
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
//        konek koneksi = new konek();
//        try{
//            conn = koneksi.configDB();
//            
//            String sql1="insert into sepatu values (?,?,?,?,?,?,?)";
//            PreparedStatement pst = conn.prepareStatement(sql1);
//            
//            pst.setString(1, (String) cmbbrand.getSelectedItem());
//            pst.setString(2, (String) cmblocal.getSelectedItem());
//            pst.setString(3, (String) cmbinter.getSelectedItem());
//            pst.setString(4, (String) tkode.getText());
//            pst.setString(5, (String) tnamaproduk.getText());
//            pst.setString(6, (String) twarna.getText());
//            pst.setString(7, (String) tsize.getText());
//            pst.setString(8, (String) tharga.getText());
//            pst.execute();
//            
//            int a = pst.executeUpdate();
//            
//            if (a == 1){
//                JOptionPane.showMessageDialog(null, "Sepatu "+ tnamaproduk.getText()
//                        +" berhasil ditambahkan!");
//            }
//        }catch (HeadlessException | SQLException ex){
//            JOptionPane.showMessageDialog(null, "Data belum terisi semua!");
//        }
    }//GEN-LAST:event_btaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btabout;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btcatalog;
    private javax.swing.JButton btdata;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btlogout;
    private javax.swing.JButton btmenu;
    private javax.swing.JComboBox<String> cmbbrand;
    private javax.swing.JComboBox<String> cmblocal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tnamaproduk;
    private javax.swing.JTextField tsize;
    private javax.swing.JTextField twarna;
    // End of variables declaration//GEN-END:variables
}
