/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.glass.events.KeyEvent;
import objectpage.*;

/**
 *
 * @author ASUS
 */
public class catalogpage extends javax.swing.JFrame {

    /**
     * Creates new form catalogpage
     */
    public catalogpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tsearch = new javax.swing.JTextField();
        btlogout = new javax.swing.JButton();
        bthome = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btdata = new javax.swing.JButton();
        btabout = new javax.swing.JButton();
        btcompass = new javax.swing.JButton();
        btnah = new javax.swing.JButton();
        btpiero = new javax.swing.JButton();
        btventela = new javax.swing.JButton();
        btbalenciaga = new javax.swing.JButton();
        btnike = new javax.swing.JButton();
        btyeezy = new javax.swing.JButton();
        btlv = new javax.swing.JButton();
        btinter = new javax.swing.JButton();
        btlocal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tsearch.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tsearch.setBorder(null);
        tsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tsearchKeyPressed(evt);
            }
        });
        getContentPane().add(tsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 26, 310, 50));

        btlogout.setContentAreaFilled(false);
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 29, 70, 50));

        bthome.setContentAreaFilled(false);
        bthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthomeActionPerformed(evt);
            }
        });
        getContentPane().add(bthome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 70));

        btadd.setContentAreaFilled(false);
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        getContentPane().add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 80, 70));

        btdata.setContentAreaFilled(false);
        btdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdataActionPerformed(evt);
            }
        });
        getContentPane().add(btdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 469, 80, 70));

        btabout.setContentAreaFilled(false);
        btabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaboutActionPerformed(evt);
            }
        });
        getContentPane().add(btabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 80, 70));

        btcompass.setContentAreaFilled(false);
        btcompass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcompassActionPerformed(evt);
            }
        });
        getContentPane().add(btcompass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 80, 80));

        btnah.setContentAreaFilled(false);
        btnah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnahActionPerformed(evt);
            }
        });
        getContentPane().add(btnah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 90, 80));

        btpiero.setContentAreaFilled(false);
        btpiero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpieroActionPerformed(evt);
            }
        });
        getContentPane().add(btpiero, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 90, 80));

        btventela.setContentAreaFilled(false);
        btventela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btventelaActionPerformed(evt);
            }
        });
        getContentPane().add(btventela, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 399, 90, 80));

        btbalenciaga.setContentAreaFilled(false);
        btbalenciaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbalenciagaActionPerformed(evt);
            }
        });
        getContentPane().add(btbalenciaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 80, 70));

        btnike.setContentAreaFilled(false);
        btnike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnikeActionPerformed(evt);
            }
        });
        getContentPane().add(btnike, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 90, 60));

        btyeezy.setContentAreaFilled(false);
        btyeezy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btyeezyActionPerformed(evt);
            }
        });
        getContentPane().add(btyeezy, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 80, 70));

        btlv.setContentAreaFilled(false);
        btlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlvActionPerformed(evt);
            }
        });
        getContentPane().add(btlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 559, 90, 70));

        btinter.setContentAreaFilled(false);
        btinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinterActionPerformed(evt);
            }
        });
        getContentPane().add(btinter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 110, 490));

        btlocal.setContentAreaFilled(false);
        btlocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlocalActionPerformed(evt);
            }
        });
        getContentPane().add(btlocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 110, 490));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard_1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsearchKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER);
        String cari = tsearch.getText();
        if(cari.equals("Louis vuitton")||cari.equals("lv")){
            new LVpage().setVisible(true);
            this.dispose();
        }else if(cari.equals("nike")){
            new nikepage().setVisible(true);
            this.dispose();
        }else if(cari.equals("Yeezy")||cari.equals("yeezy")){
            new yeezypage().setVisible(true);
            this.dispose();
        }else if(cari.equals("balenciaga")||cari.equals("Balenciaga")){
            new balenciagapage().setVisible(true);
            this.dispose();
        }else if(cari.equals("Compass")||cari.equals("compass")){
            new compasspage().setVisible(true);
            this.dispose();
        }else if(cari.equals("piero")||cari.equals("Piero")){
            new pieropage().setVisible(true);
            this.dispose();
        }else if(cari.equals("nah project")||cari.equals("Nah project")){
            new Nahpage().setVisible(true);
            this.dispose();
        }else if(cari.equals("Ventela")||cari.equals("ventela")){
            new ventelapage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tsearchKeyPressed

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
        new login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlogoutActionPerformed

    private void bthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthomeActionPerformed
        new Menupage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bthomeActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        new addpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btaddActionPerformed

    private void btdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdataActionPerformed
       new datapage().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btdataActionPerformed

    private void btaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaboutActionPerformed
        new aboutpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btaboutActionPerformed

    private void btventelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btventelaActionPerformed
        new ventelapage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btventelaActionPerformed

    private void btnahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnahActionPerformed
        new Nahpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnahActionPerformed

    private void btpieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpieroActionPerformed
        new pieropage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btpieroActionPerformed

    private void btbalenciagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbalenciagaActionPerformed
        new balenciagapage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbalenciagaActionPerformed

    private void btcompassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcompassActionPerformed
        new compasspage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcompassActionPerformed

    private void btnikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnikeActionPerformed
        new nikepage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnikeActionPerformed

    private void btyeezyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btyeezyActionPerformed
        new yeezypage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btyeezyActionPerformed

    private void btlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlvActionPerformed
        new LVpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlvActionPerformed

    private void btinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinterActionPerformed
        new balenciagapage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btinterActionPerformed

    private void btlocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlocalActionPerformed
        new compasspage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlocalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catalogpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catalogpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catalogpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catalogpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catalogpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btabout;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btbalenciaga;
    private javax.swing.JButton btcompass;
    private javax.swing.JButton btdata;
    private javax.swing.JButton bthome;
    private javax.swing.JButton btinter;
    private javax.swing.JButton btlocal;
    private javax.swing.JButton btlogout;
    private javax.swing.JButton btlv;
    private javax.swing.JButton btnah;
    private javax.swing.JButton btnike;
    private javax.swing.JButton btpiero;
    private javax.swing.JButton btventela;
    private javax.swing.JButton btyeezy;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tsearch;
    // End of variables declaration//GEN-END:variables
}
