/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.konek;

/**
 *
 * @author ASUS
 */
public class historypage extends javax.swing.JFrame {

    public DefaultTableModel model;
    public Statement st;
    public Connection conn;
    public ResultSet rs;
    
    public historypage() {
        initComponents();
        
        String[] header = {"Kode","Brand","Product","Nama Product","Warna",
        "Ukuran","Harga","Nama","Alamat"};
        
        model = new DefaultTableModel(header,0);
        tampil();
        tabelorder.setModel(model);
    }
    
    public void tampil(){
        try{
       konek koneksi = new konek();
       conn = koneksi.configDB();
       st = conn.createStatement();
       String sql = "SELECT * FROM riwayat";
       rs = st.executeQuery(sql);
       while(rs.next()){
           Object[] obj = new Object[15];
           obj[0] = rs.getString("Kode");
           obj[1] = rs.getString("Brand");
           obj[2] = rs.getString("Product");
           obj[3] = rs.getString("Nama Product");
           obj[4] = rs.getString("Warna");
           obj[5] = rs.getString("Ukuran");
           obj[6] = rs.getString("Harga");
           obj[7] = rs.getString("Nama");
           obj[8] = rs.getString("Alamat");
           
           model.addRow(obj);
       }
       }catch (Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btdata = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelorder = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btdata.setContentAreaFilled(false);
        btdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdataActionPerformed(evt);
            }
        });
        getContentPane().add(btdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 90, 20));

        tabelorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelorder);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 820, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/orderhistory.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdataActionPerformed
        new datapage().setVisible(true);
        dispose();
    }//GEN-LAST:event_btdataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(historypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(historypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(historypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(historypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new historypage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelorder;
    // End of variables declaration//GEN-END:variables
}
