/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import objectpage.*;

/**
 *
 * @author ASUS
 */
public class Menupage extends javax.swing.JFrame {

    
    /**
     * Creates new form Menupage
     */
    public Menupage() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btlogout = new javax.swing.JButton();
        btcari = new javax.swing.JButton();
        tsearch = new javax.swing.JTextField();
        btcatalog = new javax.swing.JButton();
        btadd = new javax.swing.JButton();
        btdata = new javax.swing.JButton();
        btabout = new javax.swing.JButton();
        btlv = new javax.swing.JButton();
        btnah = new javax.swing.JButton();
        btpiero = new javax.swing.JButton();
        btcompass = new javax.swing.JButton();
        btnike = new javax.swing.JButton();
        btventela = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btlogout.setContentAreaFilled(false);
        btlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, 50, 60));

        btcari.setContentAreaFilled(false);
        getContentPane().add(btcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 50, 50));

        tsearch.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tsearch.setBorder(null);
        tsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsearchActionPerformed(evt);
            }
        });
        tsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tsearchKeyPressed(evt);
            }
        });
        getContentPane().add(tsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 26, 280, 50));

        btcatalog.setContentAreaFilled(false);
        btcatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcatalogActionPerformed(evt);
            }
        });
        getContentPane().add(btcatalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 70));

        btadd.setContentAreaFilled(false);
        btadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaddActionPerformed(evt);
            }
        });
        getContentPane().add(btadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 359, 100, 70));

        btdata.setContentAreaFilled(false);
        btdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdataActionPerformed(evt);
            }
        });
        getContentPane().add(btdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 469, 100, 70));

        btabout.setText("1");
        btabout.setActionCommand("");
        btabout.setContentAreaFilled(false);
        btabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaboutActionPerformed(evt);
            }
        });
        getContentPane().add(btabout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 100, 60));

        btlv.setContentAreaFilled(false);
        btlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlvActionPerformed(evt);
            }
        });
        getContentPane().add(btlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 80, 80));

        btnah.setContentAreaFilled(false);
        btnah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnahActionPerformed(evt);
            }
        });
        getContentPane().add(btnah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 90, 80));

        btpiero.setActionCommand("");
        btpiero.setContentAreaFilled(false);
        btpiero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpieroActionPerformed(evt);
            }
        });
        getContentPane().add(btpiero, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 399, 80, 80));

        btcompass.setActionCommand("");
        btcompass.setContentAreaFilled(false);
        btcompass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcompassActionPerformed(evt);
            }
        });
        getContentPane().add(btcompass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 559, 100, 70));

        btnike.setActionCommand("");
        btnike.setContentAreaFilled(false);
        btnike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnikeActionPerformed(evt);
            }
        });
        getContentPane().add(btnike, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 90, 70));

        btventela.setActionCommand("");
        btventela.setContentAreaFilled(false);
        btventela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btventelaActionPerformed(evt);
            }
        });
        getContentPane().add(btventela, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 559, 80, 70));

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.jpg"))); // NOI18N
        jlabel.setText("jLabel1");
        getContentPane().add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        setSize(new java.awt.Dimension(1222, 756));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btcatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcatalogActionPerformed
        catalogpage catalog = new catalogpage();
        catalog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcatalogActionPerformed

    private void btaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaddActionPerformed
        addpage add = new addpage();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btaddActionPerformed

    private void btdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdataActionPerformed
        datapage data = new datapage();
        data.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btdataActionPerformed

    private void btaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaboutActionPerformed
        aboutpage about = new aboutpage();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btaboutActionPerformed

    private void btlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogoutActionPerformed
        login login = new login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlogoutActionPerformed

    private void btlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlvActionPerformed
        LVpage lv = new LVpage();
        lv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlvActionPerformed

    private void btnahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnahActionPerformed
        Nahpage nah = new Nahpage();
        nah.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnahActionPerformed

    private void btpieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpieroActionPerformed
        pieropage piero = new pieropage();
        piero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btpieroActionPerformed

    private void btcompassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcompassActionPerformed
        compasspage cmps = new compasspage();
        cmps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcompassActionPerformed

    private void btnikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnikeActionPerformed
        nikepage nike = new nikepage();
        nike.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnikeActionPerformed

    private void btventelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btventelaActionPerformed
        ventelapage ven = new ventelapage();
        ven.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btventelaActionPerformed

    private void tsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsearchKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER);
        String cari = tsearch.getText();
        if(cari.equals("Louis vuitton")||cari.equals("lv")){
            new LVpage().setVisible(true);
            this.dispose();
        }else if(cari.equals("nike")){
            new nikepage().setVisible(true);
            this.dispose();
        }else if(cari.equals("Yeezy")||cari.equals("yeezy")){
            new yeezypage().setVisible(true);
            this.dispose();
        }else if(cari.equals("balenciaga")||cari.equals("Balenciaga")){
            new balenciagapage().setVisible(true);
            this.dispose();
        }else if(cari.equals("Compass")||cari.equals("compass")){
            new compasspage().setVisible(true);
            this.dispose();
        }else if(cari.equals("piero")||cari.equals("Piero")){
            new pieropage().setVisible(true);
            this.dispose();
        }else if(cari.equals("nah project")||cari.equals("Nah project")){
            new Nahpage().setVisible(true);
            this.dispose();
        }else if(cari.equals("Ventela")||cari.equals("ventela")){
            new ventelapage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tsearchKeyPressed

    private void tsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menupage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btabout;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btcari;
    private javax.swing.JButton btcatalog;
    private javax.swing.JButton btcompass;
    private javax.swing.JButton btdata;
    private javax.swing.JButton btlogout;
    private javax.swing.JButton btlv;
    private javax.swing.JButton btnah;
    private javax.swing.JButton btnike;
    private javax.swing.JButton btpiero;
    private javax.swing.JButton btventela;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField tsearch;
    // End of variables declaration//GEN-END:variables
}
