/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package objectpage;

import GUI.*;
import javax.swing.table.DefaultTableModel;
import objectclass.*;
/**
 *
 * @author ASUS
 */
public class compasspage extends javax.swing.JFrame {
    
    private local lc;

    /**
     * Creates new form compasspage
     */
    public compasspage() {
        initComponents();
        
        String[] header = {"Kode","Brand","Product",
            "Nama Product","Warna","Ukuran","Harga"};
        
        lc = new compass();
        lc.model = new DefaultTableModel(header,0);
        
        lc.cetak();
        tabel.setModel(lc.model);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btback = new javax.swing.JButton();
        btpiero = new javax.swing.JButton();
        btventela = new javax.swing.JButton();
        btnah = new javax.swing.JButton();
        btbeli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btback.setContentAreaFilled(false);
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        getContentPane().add(btback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 30));

        btpiero.setContentAreaFilled(false);
        btpiero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpieroActionPerformed(evt);
            }
        });
        getContentPane().add(btpiero, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 90, 80));

        btventela.setContentAreaFilled(false);
        btventela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btventelaActionPerformed(evt);
            }
        });
        getContentPane().add(btventela, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 80, 80));

        btnah.setContentAreaFilled(false);
        btnah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnahActionPerformed(evt);
            }
        });
        getContentPane().add(btnah, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 80, 80));

        btbeli.setContentAreaFilled(false);
        btbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbeliActionPerformed(evt);
            }
        });
        getContentPane().add(btbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 840, 260, 30));

        tabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setRowHeight(25);
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 1040, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/compasspage.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        new catalogpage().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btbackActionPerformed

    private void btnahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnahActionPerformed
        new Nahpage().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnahActionPerformed

    private void btpieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpieroActionPerformed
        new pieropage().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btpieroActionPerformed

    private void btventelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btventelaActionPerformed
        new ventelapage().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btventelaActionPerformed

    private void btbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbeliActionPerformed
        new buypage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compasspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compasspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compasspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compasspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new compasspage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btbeli;
    private javax.swing.JButton btnah;
    private javax.swing.JButton btpiero;
    private javax.swing.JButton btventela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
