/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package objectpage;

import GUI.*;
import javax.swing.table.DefaultTableModel;
import objectclass.*;

/**
 *
 * @author ASUS
 */
public class yeezypage extends javax.swing.JFrame {
    
    private interclass in;

    /**
     * Creates new form yeezypage
     */
    public yeezypage() {
        initComponents();
        
        String[] header = {"Kode","Brand","Product",
            "Nama Product","Warna","Ukuran","Harga"};
        
        in = new yeezy();
        in.model = new DefaultTableModel(header,0);
        
        in.cetak();
        tabel.setModel(in.model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnike = new javax.swing.JButton();
        btbalen = new javax.swing.JButton();
        btlv = new javax.swing.JButton();
        btback = new javax.swing.JButton();
        btbeli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnike.setContentAreaFilled(false);
        btnike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnikeActionPerformed(evt);
            }
        });
        getContentPane().add(btnike, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 90, 70));

        btbalen.setContentAreaFilled(false);
        btbalen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbalenActionPerformed(evt);
            }
        });
        getContentPane().add(btbalen, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 119, 90, 70));

        btlv.setContentAreaFilled(false);
        btlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlvActionPerformed(evt);
            }
        });
        getContentPane().add(btlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 90, 70));

        btback.setContentAreaFilled(false);
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        getContentPane().add(btback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 40));

        btbeli.setContentAreaFilled(false);
        btbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbeliActionPerformed(evt);
            }
        });
        getContentPane().add(btbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 840, 300, 40));

        tabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setRowHeight(25);
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 637, 1120, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/yeezypage.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        new catalogpage().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btbackActionPerformed

    private void btbalenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbalenActionPerformed
        new balenciagapage().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btbalenActionPerformed

    private void btlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlvActionPerformed
        new LVpage().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btlvActionPerformed

    private void btnikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnikeActionPerformed
        new nikepage().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnikeActionPerformed

    private void btbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbeliActionPerformed
        new buypage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yeezypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yeezypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yeezypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yeezypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yeezypage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btbalen;
    private javax.swing.JButton btbeli;
    private javax.swing.JButton btlv;
    private javax.swing.JButton btnike;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
