/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import objectclass.*;
/**
 *
 * @author ASUS
 */
public class buypage extends javax.swing.JFrame {
    
    private pembeli cust;

    /**
     * Creates new form buypage
     */
    public buypage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tkode = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();
        tno = new javax.swing.JTextField();
        btdis = new javax.swing.JButton();
        btcekout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tkode.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tkode.setBorder(null);
        getContentPane().add(tkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 120, 30));

        temail.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        temail.setBorder(null);
        getContentPane().add(temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 350, 30));

        tnama.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tnama.setBorder(null);
        getContentPane().add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 350, -1));

        talamat.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        talamat.setBorder(null);
        getContentPane().add(talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 350, -1));

        tno.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tno.setBorder(null);
        getContentPane().add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 350, -1));

        btdis.setContentAreaFilled(false);
        btdis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdisActionPerformed(evt);
            }
        });
        getContentPane().add(btdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 150, 30));

        btcekout.setContentAreaFilled(false);
        btcekout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcekoutActionPerformed(evt);
            }
        });
        getContentPane().add(btcekout, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/formbeli_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btdisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdisActionPerformed
        dispose();
    }//GEN-LAST:event_btdisActionPerformed

    private void btcekoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcekoutActionPerformed
         cust = new pembeli();
        
        cust.setname(tnama.getText());
        cust.setalamat(talamat.getText());
        cust.setnohp(tno.getText());
        cust.setemail(temail.getText());
        
        cust.beli();
        cust.beli(tkode.getText());
        new Menupage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btcekoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buypage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcekout;
    private javax.swing.JButton btdis;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tkode;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tno;
    // End of variables declaration//GEN-END:variables
}
