/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */
public class regispage extends javax.swing.JFrame {
    Connection conn= null;
    Statement st=null;

   
    /**
     * Creates new form regispage
     */
    public regispage() {
        initComponents();
    }
    
    private void hapuslayar(){
        tuser.setText("");
        tname.setText("");
        tpass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpass = new javax.swing.JTextField();
        tuser = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpass.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tpass.setBorder(null);
        getContentPane().add(tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 320, 40));

        tuser.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tuser.setBorder(null);
        getContentPane().add(tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 320, 40));

        tname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        tname.setBorder(null);
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 320, 40));

        btnsave.setContentAreaFilled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 140, 30));

        btncancel.setContentAreaFilled(false);
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 629, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/regispage.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 700));

        setSize(new java.awt.Dimension(400, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        new login().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try{
            if(tuser.getText().equals("")||tname.getText().equals("")||
                    tpass.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
                hapuslayar();
            }else{
                Class.forName("com.mysql.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/sneakydb","root","");
                st = conn.createStatement();
                String simpan = "insert into dblogin values ('"+tname.getText()+"','"+tpass.getText()+"')";
                st = conn.createStatement();
                int SA = st.executeUpdate(simpan);
                JOptionPane.showMessageDialog(null, "Registrasi Berhasil!");
                this.setVisible(false);
                new login().setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Akun Sudah ada");
            hapuslayar();
        }
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regispage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regispage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regispage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regispage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regispage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tpass;
    private javax.swing.JTextField tuser;
    // End of variables declaration//GEN-END:variables
}
